module.exports.welcomeController = require('./welcome')
module.exports.accountController = require('./account')
module.exports.productController = require('./product')
module.exports.cartController = require('./cart')
module.exports.contactController = require('./contact')